window.BOT_CONFIG = {
  oddsApiKey: "replace_me",
  balldontlieApiKey: "replace_me",
  sportradarApiKey: "replace_me",
  sportsdataApiKey: "replace_me",
  pythonExecutable: "python",
  theRundownApiKey: "replace_me",
  telegramBotToken: "replace_me",
  telegramChatId: "replace_me",
  oddsRegion: "us",
  oddsMarkets: "h2h,spreads,totals",
  oddsNbaPropsMarkets: "player_points,player_rebounds,player_assists,player_threes",
  oddsNflPropsMarkets: "player_pass_yds,player_pass_tds,player_rush_yds,player_reception_yds,player_anytime_td",
  nflSeasonOverride: 2026,
  nflWeekOverride: 1,
  sportsDataIoNflPlayerProjectionUrl: "https://api.sportsdata.io/v3/nfl/projections/json/PlayerGameProjectionStatsByWeek/{season}/{week}",
  sportsDataIoNflPlayerGameStatsUrl: "https://api.sportsdata.io/v3/nfl/stats/json/PlayerGameStatsByWeek/{season}/{week}",
  sportsDataIoMlbLineupsUrl: "https://api.sportsdata.io/v3/mlb/projections/json/StartingLineupsByDate/{date}",
};
